language: groovy
sudo: required

branches:
  only:
  - master

env:
  global:
    MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
cache:
  directories:
  - $HOME/.m2

services:
  - docker

before_install:
  - docker pull squidfunk/mkdocs-material

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - mvn verify --batch-mode
  - |
    if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]
    then
       docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/docs -w /docs/documentation squidfunk/mkdocs-material build --clean --verbose --strict
    else
      # Only in case we are in master branch of the leading SAP repo we would like to deploy,
      # not from the forks.
      if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_REPO_SLUG}" == "SAP/jenkins-library" ]]
      then
         echo "Found change on master: Deployment of documentation"
         PRIVATE_KEY="cfg/id_rsa"
         openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in cfg/id_rsa.enc -out "${PRIVATE_KEY}" -d
         chmod a+x gh-pages-deploy.sh
         docker run --rm -it --entrypoint "./gh-pages-deploy.sh" -e "TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}" -v ${TRAVIS_BUILD_DIR}:/docs -w /docs squidfunk/mkdocs-material
      else
         echo "Publishing documentation skipped."
      fi
    fi

after_success:
  - mvn -DrepoToken=$COVERALLS_REPO_TOKEN org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report

after_script:
  - JACOCO_SOURCE_PATH="src vars test" ./cc-test-reporter format-coverage target/site/jacoco/jacoco.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage
